apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
spec:
  template:
    spec:
      containers:
      - name: todolist
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi