apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas | default .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      initContainers:
      - name: wait-for-backend
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup {{ .Values.backend.name }}-svc; do echo waiting for backend; sleep 2; done;']
      containers:
      - name: vue-ui
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ .Values.frontend.name }}-config
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - port: 80
    targetPort: 8080