apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.database.name }}-netpol
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.database.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.backend.name }}
    - podSelector:
        matchLabels:
          app: {{ .Values.webui.name }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.frontend.name }}-netpol
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.backend.name }}-netpol
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.backend.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.webui.name }}-netpol
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.webui.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}