apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.database.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webui.name }}-secret
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.database.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.password | b64enc }}